apiVersion: v1
kind: Service
metadata:
  name: oidctest
  namespace: argocd
  labels:
    app: oidctest
spec:
  ports:
  - port: 5000
    protocol: TCP
    name: flask
  selector:
    app: oidctest
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oidc-deployment
  namespace: argocd
  labels:
    app: oidctest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oidctest
      tier: frontend
  template:
    metadata:
      labels:
        app: oidctest
        tier: frontend
    spec: # Pod spec
      containers:
      - name: oidc-container
        image: condorl/oidcmobilefactory:v2.0
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "16Mi"
            cpu: "50m"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: domain-ingress
  namespace : argocd
spec:
  rules:
  - host: mobilefactory.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: oidctest
            port:
              name: flask

