apiVersion: v1
kind: Service
metadata:
  name: oidctest-lb
  namespace: argocd
  annotations:
    cloud.google.com/load-balancer-type: "internal"
  labels:
    app: oidctest
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    name: flask
  selector:
    app: oidctest
---
apiVersion: v1
kind: Service
metadata:
  name: iodc-lb-dns
  namespace: argocd
spec:
  type: ExternalName
  externalName: oidctest-lb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oidc-deployment
  namespace: argocd
  labels:
    app: oidctest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oidctest
      tier: frontend
  template:
    metadata:
      labels:
        app: oidctest
        tier: frontend
    spec: # Pod spec
      containers:
      - name: oidc-container
        image: condorl/oidcmobilefactory:v2.0
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "16Mi"
            cpu: "50m"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: domain-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host: mobilefactory.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: iodc-lb-dns
            port:
              name: flask
